### ISSUE TITLE
STM32H743I-EVAL2 , CYW4343W

### ISSUE THREAD

**Issue by NEXTY-ELE** [Infineon/AIROC-Wi-Fi-Bluetooth-STM32#3]
** Did you find the answer? ** **

No. I couldn't find it

** Question / Problem **:

I built and ran STM32H743I-EVAL2 and CYW4343W according to this document.
But it fails in the WiFiTask function (stm32_cypal_wifi_sdio_init)

Do I need to make any additional settings for GPIO or SDMMC?

**environment**

STM32CubeMX v6.3
STM32 Connectivity Expansion Pack 1.1.0
SDMMC1(SD 4bit wide bus)

EWARM v9.20

STM32H743I-EVAL2
muRata uSD-M2 + CYW4343W

Thanks!

**Comment by Aditi1091998** [comment]
Hi,

Is the build going through successfully?

Thanks
