### ISSUE TITLE
Does this expansion pack provide support for USB interface for STM32F4 with CYW4373E?

### ISSUE THREAD

**Issue by sherinds** [Infineon/AIROC-Wi-Fi-Bluetooth-STM32#7]
**Have you looked for an answer?**

We appreciate you checking the documentation, release notes, or the Developer community before asking. Please tell us where you looked, so we can fill the gap and help the next person too.

**Question/Issue**:

What can we help you with?

**Context**

Let us know about your environment, any information that may help us answer correctly the first time. Perhaps: the chip or kit, your host OS, what IDE you're using, the compiler, the debug probe, anything that you think might affect the answer.

**Where did you expect to find the answer?**

**Comment by IPR7** [comment]
Hi,

The latest release of expansion pack supports STM32L5xx, STM32H7xx series of MCU's to be interfaced with Infineon WiFi chips. As of now, STM32F4 MCU's are not supported.

Thanks
