### ISSUE TITLE
Help to provide a stm32f429+cyw43438 program

### ISSUE THREAD

**Issue by asngj** [Infineon/AIROC-Wi-Fi-Bluetooth-STM32#8]
I reviewed the documentation provided，STM32ConnectivityExpansionPack_UserGuide，but The compilation encountered a lot of problems。Help to provide a program reference of stm32f429+cyw43438,example wifi_scan and ble_wifi_onboarding ，The project is urgent.The hardware connection is as follows.
   /**SDIO GPIO Configuration
    PC8     ------> SDIO_D0
    PC9     ------> SDIO_D1
    PC10     ------> SDIO_D2
    PC11     ------> SDIO_D3
    PC12     ------> SDIO_CK
    PD2     ------> SDIO_CMD
/**USART2 GPIO Configuration
    PD3     ------> USART2_CTS
    PD4     ------> USART2_RTS
    PD5     ------> USART2_TX
    PD6     ------> USART2_RX

/********REGON************/

BT_REG_ON    PC4
WL_REG_ON   PB5

I am grateful for your help.

**Comment by acharyamayur** [comment]
Hi @asngj 

Unfortunately, the STM connectivity expansion pack **does not** support STM32F429 **at present**. However, you may check the user guide to learn about the supported STM32 MCU families and boards.

Hope that helps!

**Comment by asngj** [comment]
hi @acharyamayur
   I generated the program cyw43438+stm32f4 according to the document,but,The compilation encountered some problems
Many SDIo-related variables in stm32_cyhal_sdio.c start with SDMMC_, but actually all sdio variables in the stm32f4 project start with SDIO_;It's very difficult to change, The source code is as follows。
 链接：https://pan.baidu.com/s/1k4y0M748voPI7ioqAYSgYA 
提取码：iw8r 
--来自百度网盘超级会员V6的分享
Can I make a formal case for you? Please leave your email addres。

I am grateful for your help.

**Comment by acharyamayur** [comment]
Hi @asngj,

Apologies for the delay in reply.
As we have not experimented porting with STM32 F series MCUs, even we are not completely aware of the issues presented by you. I am discussing about this internally and will update you with helpful pointers, if any. I'll definitely take the feedback to the internal team to provide some guidelines for the STM32F4x series.

As for creating a formal case, feel free to do so over myInfineon platform.

Thank you for your patience!
