### ISSUE TITLE
Performance issue when working with Wifi Murata 1DX(CYW43430) and Nucleo STM32U575 board

### ISSUE THREAD

**Issue by AshwiniMShinde-eaton** [Infineon/AIROC-Wi-Fi-Bluetooth-STM32#9]
**Question/Issue**:

Performance issue when working with Wifi Murata 1DX(CYW43430) and Nucleo STM32U575 board

**Context**

I'm trying to test wifi scan example with nucleo STM32U575 board and wifi CYW4343 module over SDIO/SDMMC interface. SDIO/SDMMC frequency is 25MHz and the code uses zephyr RTOS. I've observed that WLAN firmware download takes about 43 seconds to complete which is quite long.

I have another setup with Nebula board that uses STM32F429 and wifi CYW4343 module. It also uses the same code except SDIO IDMA. As IDMA is absent in STM32F4, I've configured DMA2_Stream3 for SDIO. SDIO/SDMMC frequency is 25MHz and the code uses zephyr RTOS. In this case, WLAN firmware download takes about 2-3 seconds. I wound like to know what is contributing to the difference in performance? What is the optimal time that STM32U575 should take for WLAN firmware download if it was tested on your side already?

**Comment by Aditi1091998** [comment]
The issue is resolved on the customer's end. The issue was caused due to a semaphore during the bulk transfer function
